// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhR8lZ9E6nTmeGhDzaBY4wgkLTQ2KMoBY',
    appId: '1:340887494341:web:c65e15b3c5565d5029daac',
    messagingSenderId: '340887494341',
    projectId: 'auth-firebase-lesson-a0b63',
    authDomain: 'auth-firebase-lesson-a0b63.firebaseapp.com',
    storageBucket: 'auth-firebase-lesson-a0b63.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCVRdGIT0S52E_1haj9bu_Up7fUPmtXNdg',
    appId: '1:340887494341:android:d45c44e9d391af4429daac',
    messagingSenderId: '340887494341',
    projectId: 'auth-firebase-lesson-a0b63',
    storageBucket: 'auth-firebase-lesson-a0b63.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBgxWEGcumlg8NQaiV6jvc4uqNgga_7EUU',
    appId: '1:340887494341:ios:b5a13f5d66060b6829daac',
    messagingSenderId: '340887494341',
    projectId: 'auth-firebase-lesson-a0b63',
    storageBucket: 'auth-firebase-lesson-a0b63.appspot.com',
    iosClientId: '340887494341-pep08p19j77gupijnqteojl2idp6th1t.apps.googleusercontent.com',
    iosBundleId: 'com.example.lesson36FirebaseAuth',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBgxWEGcumlg8NQaiV6jvc4uqNgga_7EUU',
    appId: '1:340887494341:ios:9ce1487188e858f129daac',
    messagingSenderId: '340887494341',
    projectId: 'auth-firebase-lesson-a0b63',
    storageBucket: 'auth-firebase-lesson-a0b63.appspot.com',
    iosClientId: '340887494341-noa6lt6b9sfss6lt7hjbp11o0j6o68qd.apps.googleusercontent.com',
    iosBundleId: 'com.example.lesson36FirebaseAuth.RunnerTests',
  );
}
